[build]
builder = "nixpacks"
engines = { python = "3.11" }

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["pip install -r requirements.txt", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "uvicorn backend:app --host 0.0.0.0 --port 8000"

[env]
PORT = "8000"