services:
  - type: web
    name: todoevents
    env: node
    rootDir: frontend
    buildCommand: npm ci && npm run build
    startCommand: npx serve -s dist
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://todoevents-backend.onrender.com
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.x 