services:
  # Backend API service
  - type: web
    name: eventfinder-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend:app --host 0.0.0.0 --port $PORT --workers 2 --timeout-keep-alive 75
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: RAILWAY_ENVIRONMENT
        value: production
      - key: SECRET_KEY
        fromDatabase:
          name: eventfinder-db
          property: connectionString
      - key: DATABASE_POOL_SIZE
        value: 5
      - key: DATABASE_MAX_OVERFLOW
        value: 10
      - key: DATABASE_POOL_TIMEOUT
        value: 30
      - key: DATABASE_CONNECT_TIMEOUT
        value: 15
  
  # Frontend web service
  - type: web
    name: eventfinder-web
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://eventfinder-api.onrender.com
      - key: VITE_GOOGLE_MAPS_API_KEY
        sync: false
          
databases:
  - name: eventfinder-db
    databaseName: eventfinder
    plan: free
    ipAllowList: []  # only allow internal connections