services:
  - type: web
    name: todoevents-frontend
    env: node
    rootDir: frontend
    buildCommand: npm ci && npm install tailwindcss-animate && npm run build
    startCommand: npm run start
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://todoevents-backend.onrender.com 