services:
  # Backend API service
  - type: web
    name: todoevents-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: SECRET_KEY
        value: 3a4f89cc0b7db4bf2a97e6fe9f9a8e29fcb43d8f5d67c8a3
      - key: DATABASE_URL
        value: postgresql://todoevents_user:9i7NARYK2tVZI6yXXV3gOw644m2SsjuE@dpg-d0od9fbe5dus73avgsk0-a.oregon-postgres.render.com/todoevents
      - key: PORT
        value: 8000
  
  # Frontend web service
  - type: web
    name: todoevents
    env: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://todoevents-backend.onrender.com
      - key: NODE_ENV
        value: production

# Database
databases:
  - name: todoevents-db
    databaseName: todoevents
    user: todoevents_user
    plan: free