services:
  # Backend API service
  - type: web
    name: todoevents-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: PORT
        value: 8000
  
  # Frontend web service
  - type: web
    name: todoevents
    env: node
    rootDir: frontend
    buildCommand: npm ci && npm install tailwindcss-animate && npm run build
    staticPublishPath: ./dist
    startCommand: npm run start
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
# Database
databases:
  - name: todoevents-db
    databaseName: todoevents
    user: todoevents_user
    plan: free