services:
  # Backend API service
  - type: web
    name: eventfinder-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: RAILWAY_ENVIRONMENT
        value: production
      - key: SECRET_KEY
        fromDatabase:
          name: eventfinder-db
          property: connectionString
  
  # Frontend web service
  - type: web
    name: eventfinder-web
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build:render
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://eventfinder-api.onrender.com
      - key: VITE_GOOGLE_MAPS_API_KEY
        sync: false
          
databases:
  - name: eventfinder-db
    databaseName: eventfinder
    plan: free