services:
  - type: web
    name: todoevents-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python -m pip install -r requirements.txt
      uvicorn backend:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: SECRET_KEY
        value: 3a4f89cc0b7db4bf2a97e6fe9f9a8e29fcb43d8f5d67c8a3
      - key: DATABASE_URL
        value: postgresql://eventfinder_user:J6euBSG7jS6U0aPZxMjy5CfuUnOAhjj8@dpg-d0bs2huuk2gs7383mnu0-a.oregon-postgres.render.com/eventfinder
      - key: STRIPE_WEBHOOK_SECRET
        generateValue: true
      - key: STRIPE_PRICE_ID
        generateValue: true
      - key: STRIPE_ENTERPRISE_PRICE_ID
        generateValue: true 