name: TodoEvents
options:
  bundleIdPrefix: com.todoevents
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic
    PRODUCT_NAME: TodoEvents
    TARGETED_DEVICE_FAMILY: "1,2"
    SWIFT_VERSION: "5.0"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
    GENERATE_INFOPLIST_FILE: "NO"
targets:
  TodoEvents:
    type: application
    platform: iOS
    sources:
      - path: TodoEvents
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: TodoEvents/Config/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.todoevents.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SUPPORTS_MACCATALYST: "NO"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    info:
      path: TodoEvents/Config/Info.plist
    entitlements:
      path: TodoEvents/TodoEvents.entitlements
